# -*- coding: utf-8 -*-
"""
/***************************************************************************
 kataster
                                 A QGIS plugin
 kataster
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-02
        copyright            : (C) 2025 by jancabaj
        email                : jan807931@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load kataster class from file kataster.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .kataster import kataster
    return kataster(iface)
